apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-controller
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: configuration-management
  serviceAccountName: kustomize-controller
  path: ./config/infrastructure/ingress-controller
  prune: true
  wait: true
  timeout: 10m
---