roles: kube,app,discovery
authToken: a8a8452fe19d74c60d77bc354982e3f9
proxyAddr: gs-platform.teleport.sh:443
kubeClusterName: gs-platform
labels:
    teleport.internal/resource-id: 617598d4-ceb3-4b4c-99e0-7733937656f0
enterprise: true
updater:
    enabled: true
    releaseChannel: "stable/cloud"
highAvailability:
    replicaCount: 2
    podDisruptionBudget:
        enabled: true
        minAvailable: 1
