apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: default
spec:
  interval: 10m
  provider: generic
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: default
spec:
  releaseName: nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      version: '4.7.1'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: default
  interval: 5m
  values:
    controller:
      replicaCount: 2
      service:
        type: LoadBalancer
  kubeConfig:
    secretRef:
      name: dev-kubeconfig

