apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-github
spec:
  package: xpkg.upbound.io/coopnorge/provider-github:v0.13.0
---
apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: github-creds
      namespace: crossplane-system
      key: credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "token": "${GITHUB_IPD_TOKEN}",
      "owner": "mediona"
    }