apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config
  namespace: default
spec:
  interval: 10m0s
  path: ./config
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: configuration-management
  targetNamespace: default
  timeout: 3m0s
  wait: true
